### PR TITLE
Chore/php8.2

### PR DESCRIPTION
**Pull request by RobjS**
This PR introduces support for PHP 8.2 and up, and removes support for PHP 7 before 7.4.

It also adds a CHANGELOG, and migrates the linter to the standard dxw config.

### CODE REVIEW

**Review by snim2 — APPROVED** [review]
This repo doesn't have a `script/test`, but I have my own:

```shell
❯ cat script/test
#!/bin/sh

./vendor/bin/php-cs-fixer fix --dry-run -v --diff
./vendor/bin/kahlan spec
./vendor/bin/psalm --show-info=true
```

And Psalm, with that setting, shows a type issue, but I'm not sure whether it's worth fixing in this PR?

```shell
INFO: MixedReturnStatement - src/Err.php:22:10 - Could not infer a return type (see https://psalm.dev/138)
                return $default;


------------------------------

       No errors found!

------------------------------
1 other issues found.
------------------------------

Checks took 0.01 seconds and used 4.626MB of memory
No files analyzed
Psalm was able to infer types for 95.8333% of the codebase
```

**Comment by RobjS** [comment]
I don't know if we can fix that without making a breaking change, here's the problematic method:

```
public function unwrapOr($default)
{
	return $default;
}
```

So given `$default` could have any type, I think the only way we could fix it would be insisting on a specific type for the input, which could break usage cases where something other than that type is being passed in.

**Comment by snim2** [comment]
@RobjS so, I think PHP8 introduces `mixed` which is like `Any` in some other languages. I'm not sure if we can use it here or not, given we expect to be on legacy PHP for a while, but maybe we should raise an issue?

**Comment by RobjS** [comment]
@snim2 Psalm will let us add `mixed` as a type annotation, so I've done that, and it's stopped complaining 👍

**Pull request merged**
